spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_platform_dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    com.codewild.food: DEBUG
